// <auto-generated />
using System;
using GreenThumb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GreenThumb.Migrations
{
    [DbContext(typeof(GreenThumbDbContext))]
    [Migration("20231204174138_SeedAdmin")]
    partial class SeedAdmin
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GardenModelPlantModel", b =>
                {
                    b.Property<int>("GardensGardenId")
                        .HasColumnType("int");

                    b.Property<int>("PlantsPlantId")
                        .HasColumnType("int");

                    b.HasKey("GardensGardenId", "PlantsPlantId");

                    b.HasIndex("PlantsPlantId");

                    b.ToTable("GardenModelPlantModel");
                });

            modelBuilder.Entity("GreenThumb.Models.GardenModel", b =>
                {
                    b.Property<int>("GardenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("garden_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GardenId"), 1L, 1);

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("GardenId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[user_id] IS NOT NULL");

                    b.ToTable("Gardens");
                });

            modelBuilder.Entity("GreenThumb.Models.InstructionModel", b =>
                {
                    b.Property<int>("InstructionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("instruction_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstructionId"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<int>("PlantId")
                        .HasColumnType("int")
                        .HasColumnName("plant_id");

                    b.HasKey("InstructionId");

                    b.HasIndex("PlantId");

                    b.ToTable("Instruction");

                    b.HasData(
                        new
                        {
                            InstructionId = 1,
                            Description = "Deep and infrequent watering rather than frequent shallow watering. Water when the top inch of soil feels dry.",
                            Name = "Watering",
                            PlantId = 1
                        },
                        new
                        {
                            InstructionId = 2,
                            Description = "Prune in late winter or early spring to remove dead or diseased wood and shape the plant.",
                            Name = "Pruning",
                            PlantId = 1
                        },
                        new
                        {
                            InstructionId = 3,
                            Description = "Ensure the pot has drainage holes to prevent waterlogged soil.",
                            Name = "Container",
                            PlantId = 2
                        },
                        new
                        {
                            InstructionId = 4,
                            Description = "Select a location with well-draining soil and adequate sunlight.",
                            Name = "Choose the Right Location",
                            PlantId = 3
                        },
                        new
                        {
                            InstructionId = 5,
                            Description = "Ensure proper spacing between maple trees to allow for healthy growth.",
                            Name = "Spacing",
                            PlantId = 3
                        },
                        new
                        {
                            InstructionId = 6,
                            Description = "They prefer warm temperatures. Protect them from cold drafts and frost, especially during winter.",
                            Name = "Temperature",
                            PlantId = 4
                        },
                        new
                        {
                            InstructionId = 7,
                            Description = "They prefer well-draining soil. Amend heavy or compacted soil with organic matter to improve drainage.",
                            Name = "Soil",
                            PlantId = 5
                        },
                        new
                        {
                            InstructionId = 8,
                            Description = "Use a balanced, all-purpose fertilizer when planting. Additional fertilization may not be necessary if the soil is nutrient-rich.",
                            Name = "Fertilization",
                            PlantId = 5
                        },
                        new
                        {
                            InstructionId = 9,
                            Description = "Many bamboo varieties are spreading and can become invasive. Use barriers (rhizome barriers) to contain the spread of the roots.",
                            Name = "Barriers",
                            PlantId = 6
                        },
                        new
                        {
                            InstructionId = 10,
                            Description = "Mulch around the base of the palm tree to conserve moisture, regulate soil temperature, and suppress weeds.",
                            Name = "Mulching",
                            PlantId = 7
                        },
                        new
                        {
                            InstructionId = 11,
                            Description = "Ensure proper air circulation to minimize the risk of fungal diseases.",
                            Name = "Good Air Circulation",
                            PlantId = 8
                        },
                        new
                        {
                            InstructionId = 12,
                            Description = "Orchids often require higher humidity levels. In drier climates, use humidity trays, humidifiers, or group plants together to create a more humid microenvironment.",
                            Name = "Humidity",
                            PlantId = 9
                        },
                        new
                        {
                            InstructionId = 13,
                            Description = "Succulents can be propagated from leaf or stem cuttings. Allow cuttings to dry and callus before planting.",
                            Name = "Propagating",
                            PlantId = 10
                        },
                        new
                        {
                            InstructionId = 14,
                            Description = "Put it around the base of lavender to conserve soil moisture and suppress weeds.",
                            Name = "Gravel",
                            PlantId = 11
                        },
                        new
                        {
                            InstructionId = 15,
                            Description = "Plant tulip bulbs in the fall before the first frost. This allows them to establish roots before winter.",
                            Name = "Planting Time",
                            PlantId = 12
                        },
                        new
                        {
                            InstructionId = 16,
                            Description = "Ferns thrive in indirect or filtered light. Avoid exposing them to direct sunlight, especially during the hot afternoon hours.",
                            Name = "Indirect Light",
                            PlantId = 13
                        },
                        new
                        {
                            InstructionId = 17,
                            Description = "Wire branches carefully to shape and train your bonsai. Be mindful of the tree's natural growth pattern, and remove wires before they cut into the bark.",
                            Name = "Wiring",
                            PlantId = 14
                        },
                        new
                        {
                            InstructionId = 18,
                            Description = "Allow Arctic Willow to maintain its natural, arching form. Minimal pruning is needed to enhance its graceful appearance. Embrace its natural growth habit for a more authentic look.",
                            Name = "Natural Shape",
                            PlantId = 15
                        });
                });

            modelBuilder.Entity("GreenThumb.Models.PlantModel", b =>
                {
                    b.Property<int>("PlantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("plant_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlantId"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("PlantId");

                    b.ToTable("Plants");

                    b.HasData(
                        new
                        {
                            PlantId = 1,
                            Description = "The rose, a timeless symbol of love and beauty, charms with its thorny stems and a variety of velvety, fragrant blossoms in hues from deep red to soft pink and pure white.",
                            Name = "Rose"
                        },
                        new
                        {
                            PlantId = 2,
                            Description = "Aloe vera, a succulent marvel, boasts lance-shaped leaves forming a graceful rosette. Its plump, serrated foliage contains a soothing gel, blending beauty with healing virtues.",
                            Name = "Aloe Vera"
                        },
                        new
                        {
                            PlantId = 3,
                            Description = "Maple trees, with their vibrant autumnal attire, paint the landscape in hues of fiery reds, golden yellows, and burnt oranges. Graceful and iconic, their distinctively lobed leaves dance in the breeze, turning each fall day into a masterpiece of nature's artistry.",
                            Name = "Maple Tree"
                        },
                        new
                        {
                            PlantId = 4,
                            Description = "Cacti, resilient desert sculptures, wear spines like jewels, a testament to their enduring beauty in arid landscapes.",
                            Name = "Cacti"
                        },
                        new
                        {
                            PlantId = 5,
                            Description = "Sunflowers, nature's radiant sentinels, boast golden crowns that mirror the sun's warmth. Their towering stems, adorned with sunny faces, sway in rhythmic dance, embodying a field of boundless optimism and natural splendor.",
                            Name = "Sun Flower"
                        },
                        new
                        {
                            PlantId = 6,
                            Description = "Bamboo, a serene symphony of strength and grace, paints landscapes with its emerald elegance. With slender stems reaching for the sky, it whispers tales of resilience and versatility, a tranquil poetry etched in green.",
                            Name = "Bamboo"
                        },
                        new
                        {
                            PlantId = 7,
                            Description = "Palm trees, nature's ambassadors of paradise, stand tall with graceful fronds that rustle like whispers in the tropical breeze, embodying an eternal holiday under the sun.",
                            Name = "Palm Tree"
                        },
                        new
                        {
                            PlantId = 8,
                            Description = "Lilies, nature's elegant muses, unfurl their petals in a ballet of grace, each blossom a masterpiece of delicate allure, inviting admiration with their timeless beauty and enchanting fragrance.",
                            Name = "Lily"
                        },
                        new
                        {
                            PlantId = 9,
                            Description = "Orchids, ethereal dancers of the plant kingdom, grace the world with intricate blooms, a testament to nature's artistry, each blossom a delicate masterpiece, capturing hearts with their exotic allure.",
                            Name = "Orchid"
                        },
                        new
                        {
                            PlantId = 10,
                            Description = "Succulents, nature's resilient jewels, adorn arid landscapes with their plump leaves, a mosaic of vibrant hues. These water-wise wonders, sculpted by sunlight, whisper tales of endurance and beauty in the harshest of climates.",
                            Name = "Succulent"
                        },
                        new
                        {
                            PlantId = 11,
                            Description = "Lavender, a fragrant symphony in purple, weaves a tapestry of calm. Its slender stems carry blossoms that release a soothing aroma, inviting tranquility and a touch of nature's elegance to any landscape.",
                            Name = "Lavender"
                        },
                        new
                        {
                            PlantId = 12,
                            Description = "Tulips, nature's ephemeral flames, burst forth in a kaleidoscope of colors, painting the world with their vibrant petals. These graceful blooms, standing tall in a symphony of hues, epitomize the fleeting beauty of spring.",
                            Name = "Tulip"
                        },
                        new
                        {
                            PlantId = 13,
                            Description = "Ferns, nature's verdant lace, unfurl delicate fronds in a graceful dance. Their lush foliage, a testament to ancient elegance, brings a touch of timeless beauty to shaded retreats.",
                            Name = "Ferns"
                        },
                        new
                        {
                            PlantId = 14,
                            Description = "Bonsai trees, miniature emperors of serenity, embody the essence of nature in a pint-sized universe. With meticulously pruned branches and whispered stories of resilience, each tiny masterpiece breathes tranquility into its petite realm.",
                            Name = "Bonsai Tree"
                        },
                        new
                        {
                            PlantId = 15,
                            Description = "Arctic Willow, a whispering ballerina of the tundra, graces the icy landscape with its delicate, silvery branches. Amidst the frozen expanse, it stands as a testament to nature's ability to find grace and beauty in the harshest climates.",
                            Name = "Arctic Willow"
                        });
                });

            modelBuilder.Entity("GreenThumb.Models.UserModel", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit")
                        .HasColumnName("is_admin");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("username");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            IsAdmin = true,
                            Username = "admin",
                            password = "cQpKzTUoLNp8Lfr5jDxKWQ=="
                        });
                });

            modelBuilder.Entity("GardenModelPlantModel", b =>
                {
                    b.HasOne("GreenThumb.Models.GardenModel", null)
                        .WithMany()
                        .HasForeignKey("GardensGardenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GreenThumb.Models.PlantModel", null)
                        .WithMany()
                        .HasForeignKey("PlantsPlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GreenThumb.Models.GardenModel", b =>
                {
                    b.HasOne("GreenThumb.Models.UserModel", "User")
                        .WithOne("Garden")
                        .HasForeignKey("GreenThumb.Models.GardenModel", "UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GreenThumb.Models.InstructionModel", b =>
                {
                    b.HasOne("GreenThumb.Models.PlantModel", "Plant")
                        .WithMany("Instructions")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("GreenThumb.Models.PlantModel", b =>
                {
                    b.Navigation("Instructions");
                });

            modelBuilder.Entity("GreenThumb.Models.UserModel", b =>
                {
                    b.Navigation("Garden");
                });
#pragma warning restore 612, 618
        }
    }
}
